remote_theme: pmarsceill/just-the-docs
title: Karuselli
description: Customize the Sailfish OS partner space
baseurl: "/harbour-karuselli"
exclude:
  - appicons/
  - images/
  - qml/
  - rpm/
  - src/
  - tools/
  - translations/
  - assets/
  - "*.desktop"
  - "*.pro"
  - .sfdk/
  - .github/

url: "https://fravaccaro.github.io"
search_enabled: false
aux_links:
  "Karuselli on GitHub":
    - "//github.com/fravaccaro/harbour-karuselli"
